Repository mattermost/mattermost-plugin-jira, pull requests merged in 2019-11, with the labels that each got.

#361 [MM-19865] Fix modal close button to not overlap when screen is narrow
  webapp/src/components/modals/channel_settings/channel_settings_modal.scss
  webapp/src/components/modals/full_screen_modal/full_screen_modal.scss
Labels: 1: PM Review, 3: Reviews Complete

#370 [MM-19791] Fix issues with enter button deleting filter rows
  webapp/src/components/confirm_modal.tsx
  webapp/src/components/jira_epic_selector/jira_epic_selector.tsx
  webapp/src/components/modals/channel_settings/__snapshots__/edit_channel_settings.test.tsx.snap
  webapp/src/components/modals/channel_settings/channel_settings_filter.tsx
  webapp/src/components/modals/channel_settings/channel_settings_filters.tsx
  webapp/src/components/modals/channel_settings/edit_channel_settings.tsx
  webapp/src/components/modals/channel_settings/select_channel_subscription.tsx
  webapp/src/components/react_select_setting.jsx
Labels: 3: Reviews Complete

#364 [MM-18534] Resolve fields that contradict chosen issue types
  webapp/src/components/modals/channel_settings/__snapshots__/edit_channel_settings.test.tsx.snap
  webapp/src/components/modals/channel_settings/channel_settings_filter.tsx
  webapp/src/components/modals/channel_settings/channel_settings_filters.tsx
  webapp/src/components/modals/channel_settings/edit_channel_settings.test.tsx
  webapp/src/components/modals/channel_settings/edit_channel_settings.tsx
  webapp/src/utils/jira_issue_metadata.tsx
Labels: 3: Reviews Complete

#360 [MM-19706] Add "Empty" option for channel subscriptions inclusion field
  server/subscribe.go
  server/subscribe_test.go
  webapp/src/components/jira_epic_selector/__snapshots__/jira_epic_selector.test.tsx.snap
  webapp/src/components/jira_epic_selector/jira_epic_selector.tsx
  webapp/src/components/modals/channel_settings/channel_settings_filter.tsx
  webapp/src/types/model.ts
Labels: 3: Reviews Complete

#373 [MM-19072] Hide "Include All" filter for single select fields
  webapp/src/components/modals/channel_settings/channel_settings_filter.tsx
  webapp/src/utils/jira_issue_metadata.tsx
Labels: 3: Reviews Complete

#375 [MM-19802] Show associated project in select subscription modal
  webapp/src/components/modals/channel_settings/channel_settings.tsx
  webapp/src/components/modals/channel_settings/channel_settings_modal.scss
  webapp/src/components/modals/channel_settings/select_channel_subscription.tsx
  webapp/src/components/modals/channel_settings/shared_props.ts
Labels: 2: Dev Review

#376 [MM-19810] Handle default vs custom fields in events
  webapp/src/components/modals/channel_settings/__snapshots__/edit_channel_settings.test.tsx.snap
  webapp/src/components/modals/channel_settings/edit_channel_settings.tsx
  webapp/src/testdata/cloud-get-create-issue-metadata-for-project-many-fields.json
  webapp/src/utils/jira_issue_metadata.tsx
Labels: 2: Dev Review

#377 [MM-19815] When saving a subscription, remove fields that are not in the issue metadata
  webapp/src/components/modals/channel_settings/__snapshots__/edit_channel_settings.test.tsx.snap
  webapp/src/components/modals/channel_settings/edit_channel_settings.test.tsx
  webapp/src/components/modals/channel_settings/edit_channel_settings.tsx
  webapp/src/testdata/server-get-create-issue-metadata-for-project-many-fields.json
Labels: 3: Reviews Complete

#378 [MM-19903] Support Affects Version for subscription filters
  server/event_types.go
  server/issue.go
  server/webhook_parser.go
  webapp/src/components/modals/channel_settings/__snapshots__/edit_channel_settings.test.tsx.snap
  webapp/src/components/modals/channel_settings/edit_channel_settings.tsx
Labels: 3: Reviews Complete

#382 [MM-19758] Write tests for filter components
  webapp/src/components/modals/channel_settings/__snapshots__/channel_settings_filter.test.tsx.snap
  webapp/src/components/modals/channel_settings/__snapshots__/channel_settings_filters.test.tsx.snap
  webapp/src/components/modals/channel_settings/channel_settings_filter.test.tsx
  webapp/src/components/modals/channel_settings/channel_settings_filter.tsx
  webapp/src/components/modals/channel_settings/channel_settings_filters.test.tsx
  webapp/src/components/modals/channel_settings/channel_settings_filters.tsx
  webapp/src/components/react_select_setting.jsx
  webapp/src/testdata/jira-issue-metadata-helpers.ts
  webapp/src/types/model.ts
  webapp/src/utils/jira_issue_metadata.test.tsx
  webapp/src/utils/jira_issue_metadata.tsx
Labels: 3: Reviews Complete

#388 MM-20185 - Make subscription filter values not clearable
  webapp/src/components/jira_epic_selector/__snapshots__/jira_epic_selector.test.tsx.snap
  webapp/src/components/jira_epic_selector/jira_epic_selector.tsx
  webapp/src/components/modals/channel_settings/channel_settings_filter.tsx
Labels: 3: Reviews Complete

#380 [MM-20013] Improve epic link search
  server/issue.go
  webapp/src/components/jira_epic_selector/jira_epic_selector.test.tsx
  webapp/src/components/jira_epic_selector/jira_epic_selector.tsx
Labels: 3: Reviews Complete

#396 Fix snapshot after MM-20013 PR merge
  webapp/src/components/modals/channel_settings/__snapshots__/channel_settings_filter.test.tsx.snap
Labels: 3: Reviews Complete

#347 [MM-18882] Remove ephemeral message for jira server and desktop app
  webapp/src/hooks/hooks.js
  webapp/src/utils/user_agent.jsx
Labels: 3: Reviews Complete

#379 [MM-20014] Show project metadata fetch error
  webapp/.eslintrc.json
  webapp/src/actions/index.js
  webapp/src/components/modals/channel_settings/channel_settings.test.tsx
  webapp/src/components/modals/channel_settings/channel_settings.tsx
  webapp/src/components/modals/channel_settings/index.ts
  webapp/src/components/modals/channel_settings/shared_props.ts
  webapp/src/hooks/hooks.js
  webapp/src/reducers/index.js
Labels: 3: Reviews Complete

#351 Metrics
  go.mod
  go.sum
  plugin.json
  server/client.go
  server/client_test.go
  server/command.go
  server/expvar/endpoint.go
  server/expvar/endpoint_test.go
  server/expvar/http.go
  server/expvar/http_test.go
  server/expvar/stats.go
  server/expvar/stats_test.go
  server/http.go
  server/instance_cloud.go
  server/instance_server.go
  server/issue.go
  server/kv.go
  server/kv_mock_test.go
  server/plugin.go
  server/stats.go
  server/stats_test.go
  server/subscribe.go
  server/user_cloud.go
  server/utils.go
  server/utils/byte_size.go
  server/utils/limited_readcloser.go
  server/utils/limited_readcloser_test.go
  server/utils/utils.go
  server/utils/utils_test.go
  server/utils/wrap_http_client.go
  server/utils/wrap_http_client_test.go
  server/webhook_http.go
  server/webhook_jira.go
  server/webhook_worker.go
Labels: 3: Reviews Complete, Docs/Needed

#381 [MM-19689] Improve `/jira subscribe list` UX
  server/command.go
  server/subscribe.go
  server/subscribe_test.go
Labels: 3: Reviews Complete

#397 Bumped plugin version to v2.3.0
  plugin.json
  server/manifest.go
  webapp/src/manifest.ts
Labels: 3: Reviews Complete
