Repository mattermost/mattermost-plugin-jira, pull requests merged in 2019-07, with the labels that each got.

#197 [MM-16508] Fixes notifications on master; and for Jira Cloud's recent changes
  server/kv.go
  server/user_cloud.go
  server/utils.go
  server/webhook.go
  server/webhook_http.go
  server/webhook_parser.go
Labels: 2: Dev Review

#195 [MM-16503] Special handling of Reporter is broken in localized Jira
  server/issue.go
  webapp/src/components/modals/create_issue/create_issue.jsx
Labels: 2: Dev Review

#198 [MM-16680] Webhook issue comments broken on server
  server/testdata/webhook-comment-created-server.json
  server/webhook_http_test.go
  server/webhook_parser.go
Labels: 2: Dev Review

#185 [MM-16404] Fix Error Handling for Attach and Create issue Modals
  webapp/src/components/jira_issue_selector/jira_issue_selector.jsx
  webapp/src/components/modals/create_issue/create_issue.jsx
Labels: 1: PM Review, 2: Dev Review

#199 Enable coverage report
  .circleci/config.yml
  Makefile
  README.md
  server/.gitignore
Labels: 2: Dev Review

#203 [MM-16641] Attach message to issue search is broken on master
  webapp/src/client/index.js
  webapp/src/components/jira_issue_selector/jira_issue_selector.jsx
Labels: 3: Reviews Complete

#202 MM-16633 Hiding channel header button when not connected or instance not installed.
  webapp/src/components/modals/channel_settings/channel_settings.jsx
  webapp/src/components/setup_ui.js
  webapp/src/components/setup_ui/index.js
  webapp/src/components/setup_ui/setup_ui.jsx
  webapp/src/plugin.jsx
Labels: 3: Reviews Complete

#204 [MM-15902] When `/jira install` changes the instance, the UI is stuck in the previous state
  webapp/src/actions/index.js
Labels: 3: Reviews Complete

#60 [MM-15100] Add /jira assign <issue-key> <assignee> command
  server/command.go
  server/issue.go
Labels: 3: Reviews Complete

#206 Merged the missing webhook functionality from Jira2
  go.sum
  server/testdata/webhook-cloud-comment-created.json
  server/testdata/webhook-cloud-comment-deleted.json
  server/testdata/webhook-cloud-comment-updated.json
  server/testdata/webhook-issue-created-no-description-nor-relevant-fields.json
  server/testdata/webhook-issue-created-no-description.json
  server/testdata/webhook-issue-created-no-relevant-fields.json
  server/testdata/webhook-server-comment-created.json
  server/testdata/webhook-server-issue-updated-comment-deleted.json
  server/testdata/webhook-server-issue-updated-comment-edited.json
  server/testdata/webhook-server-issue-updated-commented-1.json
  server/testdata/webhook-server-issue-updated-commented-2.json
  server/webhook.go
  server/webhook_http.go
  server/webhook_http_test.go
  server/webhook_jira.go
  server/webhook_parser.go
  server/webhook_parser_misc_test.go
Labels: 2: Dev Review

#208 [MM-16108] streamlined createIssueMetadata to support 5000+ projects
  server/http.go
  server/issue.go
  webapp/src/action_types/index.js
  webapp/src/actions/index.js
  webapp/src/components/modals/channel_settings/channel_settings.jsx
  webapp/src/components/modals/channel_settings/channel_settings_internal.jsx
  webapp/src/components/modals/channel_settings/index.js
  webapp/src/components/modals/create_issue/create_issue.jsx
  webapp/src/components/modals/create_issue/index.js
  webapp/src/reducers/index.js
  webapp/src/selectors/index.js
  webapp/src/utils/jira_issue_metadata.jsx
Labels: 2: Dev Review

#210 [MM-16107] Post webhook events to channel even if no instance installed
  server/kv_mock_test.go
  server/subscribe.go
  server/webhook.go
  server/webhook_http.go
  server/webhook_http_test.go
Labels: 2: Dev Review

#211 MM-16438: fixed and slightly improved `/jira transition`
  server/command.go
  server/issue.go
  server/kv.go
Labels: 1: PM Review, 2: Dev Review

#201 [MM-15678] Add additional event support for channel subscriptions to Jira events
  server/http_test.go
  server/jira_test_util.go
  server/subscribe.go
  server/subscribe_test.go
  server/testdata/webhook-issue-deleted.json
  server/webhook_jira.go
  server/webhook_jira_test.go
  webapp/src/components/modals/channel_settings/channel_settings_internal.jsx
Labels: 1: PM Review, 2: Dev Review

#212 [MM-16688] Make DMs permissions aware
  server/webhook.go
  server/webhook_parser.go
Labels: 2: Dev Review

#213 MM-16864: added /jira info command
  server/command.go
  server/user.go
Labels: 2: Dev Review

#209 MM-16312: templatized and stylized OAuth1 error messages
  server/http.go
  server/templates/other/message.html
  server/user.go
  server/user_server.go
Labels: 1: PM Review, 2: Dev Review, Do Not Merge

#216 MM-15927: ChangeLog parsing should scan and post all supported events, not just the first one
  server/webhook.go
  server/webhook_http.go
  server/webhook_http_test.go
  server/webhook_parser.go
Labels: 1: PM Review, 2: Dev Review

#221 MM-17000: redirect from /jira install, no need to display the link
  server/command.go
Labels: 1: PM Review, 2: Dev Review

#219 MM-16870: Added PluginVersion to User, Instance, and Subscriptions KV
  server/instance.go
  server/kv.go
  server/subscribe.go
  server/user.go
  server/user_cloud.go
  server/user_server.go
Labels: 2: Dev Review

#218 MM-16540: userFriendlyJiraError
  server/command.go
  server/issue.go
Labels: 3: Reviews Complete

#224 MM-15927 ChangeLog parsing should scan and post all supported events (pt 2)
  server/webhook_http.go
  server/webhook_http_test.go
  server/webhook_parser.go
Labels: 1: PM Review, 2: Dev Review

#227 MM-16950: `JIRA` in tooltip of channel header icon should say `Jira`
  webapp/src/components/setup_ui/setup_ui.jsx
Labels: 2: Dev Review

#226 [MM-16763] Delete subscription button added to channel subscription modal
  webapp/src/action_types/index.js
  webapp/src/actions/index.js
  webapp/src/components/modals/channel_settings/channel_settings_internal.jsx
  webapp/src/reducers/index.js
Labels: 2: Dev Review

#223 Updated AccountId handling to match jira2
  server/command.go
  server/instance_cloud.go
  server/instance_server.go
  server/issue.go
  server/kv.go
  server/user.go
  server/webhook_parser.go
Labels: 2: Dev Review

#220 [MM-16887] Sync event type masks and ui values, add custom fields
  server/event_types.go
  server/http_test.go
  server/jira_test_util.go
  server/set.go
  server/subscribe.go
  server/subscribe_test.go
  server/testdata/webhook-issue-updated-custom-field.json
  server/testdata/webhook-issue-updated-fix-version.json
  server/testdata/webhook-issue-updated-issue-type.json
  server/testdata/webhook-issue-updated-multiple-custom-fields.json
  server/webhook.go
  server/webhook_http.go
  server/webhook_http_test.go
  server/webhook_jira.go
  server/webhook_jira_test.go
  server/webhook_parser.go
  server/webhook_parser_misc_test.go
  webapp/src/components/modals/channel_settings/channel_settings_internal.jsx
  webapp/src/components/modals/channel_settings/index.js
  webapp/src/components/modals/create_issue/create_issue.jsx
  webapp/src/utils/jira_issue_metadata.jsx
Labels: 2: Dev Review

#229 MM-17060: Jira Plugin: OAuth error on API calls to Jira
  go.mod
  go.sum
  server/instance_cloud.go
  server/templates/ac/atlassian-connect.json
  server/user_cloud.go
Labels: 3: Reviews Complete

#230 [MM-16887] Variable name typo fix
  webapp/src/components/modals/channel_settings/channel_settings_internal.jsx
Labels: 3: Reviews Complete

#222 MM-16881 Add ability to restrict permissions of subscribe.
  plugin.json
  server/http_test.go
  server/plugin.go
  server/subscribe.go
  webapp/src/actions/index.js
  webapp/src/client/index.js
  webapp/src/components/modals/channel_settings/channel_settings.jsx
Labels: 3: Reviews Complete

#225 MM-16002 Webhooks should process asynchronously
  server/plugin.go
  server/subscribe.go
  server/subscribe_test.go
  server/webhook_http.go
  server/webhook_parser.go
  server/webhook_parser_misc_test.go
  server/webhook_worker.go
Labels: 3: Reviews Complete

#231 MM-17060: Jira Plugin: OAuth error on API calls to Jira (#229)
  go.mod
  go.sum
  server/instance_cloud.go
  server/templates/ac/atlassian-connect.json
  server/user_cloud.go
Labels: 3: Reviews Complete

#235 Fixing conflicts.
  server/http_test.go
  server/instance.go
  server/instance_cloud.go
  server/instance_server.go
  server/kv_mock_test.go
  server/subscribe.go
Labels: 3: Reviews Complete

#228 MM-16943: Creating a new issue assigned to a user does not notify the user
  server/webhook_parser.go
Labels: 3: Reviews Complete

#236 MM-16933 Attach comment notifications for edited comments
  server/webhook_parser.go
Labels: 3: Reviews Complete

#234 Make channel subscriptions instance-specific
  server/http_test.go
  server/kv_mock_test.go
  server/subscribe.go
  server/subscribe_test.go
Labels: QA Review

#232 [MM-17061] Support multiple projects for a channel subscription
  server/http.go
  server/issue.go
  server/subscribe_test.go
  webapp/src/actions/index.js
  webapp/src/components/modals/channel_settings/channel_settings_internal.jsx
  webapp/src/components/modals/channel_settings/index.js
  webapp/src/components/modals/create_issue/create_issue.jsx
  webapp/src/components/modals/create_issue/index.js
  webapp/src/utils/jira_issue_metadata.jsx
Labels: 3: Reviews Complete

#239 [MM-17108] Correctly support custom fields correct for cloud and server
  webapp/src/utils/jira_issue_metadata.jsx
Labels: 2: Dev Review

#240 [MM-17234] Users are not receiving DMs for jira @mentions
  server/webhook_worker.go
Labels: 2: Dev Review

#241 [MM-17131] Create slash command does not work to open the modal
  webapp/src/components/modals/create_issue/create_issue.jsx
Labels: 2: Dev Review

#243 MM-17235, MM-17075 Moving to using KVCompareAndSet
  plugin.json
  server/http_test.go
  server/subscribe.go
  server/subscribe_test.go
Labels: 3: Reviews Complete

#244 MM-15908 - Updating Jira UX
  webapp/src/components/form_button.jsx
  webapp/src/components/input.jsx
  webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx
  webapp/src/components/modals/channel_settings/channel_settings_internal.jsx
  webapp/src/components/modals/create_issue/create_issue.jsx
  webapp/src/utils/styles.js
Labels: 2: Dev Review

#253 [MM-17105] Prevent channel settings modal from closing when click outside of it
  webapp/src/components/modals/channel_settings/channel_settings.jsx
Labels: 2: Dev Review

#246 [MM-17285] Subscribe modal causes blank screen on desktop
  webapp/src/components/modals/channel_settings/channel_settings_internal.jsx
  webapp/src/components/setup_ui/setup_ui.jsx
  webapp/src/utils/jira_issue_metadata.jsx
Labels: 3: Reviews Complete

#242 [MM-17041] multiple 'Jira' icons in channel header
  webapp/src/components/setup_ui/setup_ui.jsx
  webapp/src/plugin.jsx
Labels: 3: Reviews Complete

#251 [MM-17268] Subscribe permission for "Channel, Team and System Admins" treats all users as Channel Admins
  plugin.json
  server/subscribe.go
  server/utils.go
Labels: 3: Reviews Complete

#248 [MM-17295] Attach as comment should also append file attachments
  server/issue.go
  server/utils.go
Labels: 3: Reviews Complete

#254 [MM-17318] Fix for multiple icons is working, but not sure why
  webapp/src/components/setup_ui/setup_ui.jsx
  webapp/src/plugin.jsx
Labels: 3: Reviews Complete

#260 Normalize url on uninstall
  server/command.go
Labels: 3: Reviews Complete
