Repository mattermost/mattermost-plugin-jira, pull requests merged in 2019-10, with the labels that each got.

#332 [MM-19144] Prompt user to use browser to connect to Jira Cloud
  webapp/src/hooks/hooks.js
Labels: 2: Dev Review, 2: QA Review

#334 Fixed MM-19213: Issue.Self is no longer good
  server/issue_parser.go
  server/webhook.go
  server/webhook_jira.go
Labels: 3: Reviews Complete

#335 [MM-19201] Check for accountid on updateAuthor for Jira Cloud
  server/testdata/webhook-cloud-comment-deleted.json
  server/webhook_http_test.go
  server/webhook_parser.go
Labels: 3: Reviews Complete

#333 [MM-19179] Avoid react-select caching when num options is negligible
  webapp/src/components/react_select_setting.jsx
Labels: 3: Reviews Complete

#343 Revert "Prompt user to use browser to connect to Jira Cloud"
  webapp/src/hooks/hooks.js
Labels: 3: Reviews Complete

#345 Bumped plugin version to v2.2.2
  plugin.json
  server/manifest.go
  webapp/src/manifest.ts
Labels: 2: Dev Review, 2: QA Review, Do Not Merge, Docs/Not Needed

#341 [MM-18736] Add Confirm Modal for Subscription Delete Button Click
  webapp/src/components/confirm_modal.tsx
  webapp/src/components/modals/channel_settings/__snapshots__/edit_channel_settings.test.tsx.snap
  webapp/src/components/modals/channel_settings/edit_channel_settings.test.tsx
  webapp/src/components/modals/channel_settings/edit_channel_settings.tsx
  webapp/src/components/modals/channel_settings/select_channel_subscription.tsx
Labels: 2: QA Review

#331 [MM-19077] Prevent ENTER key from triggering a click on the remove, cancel and Add Filter buttons
  webapp/src/components/modals/channel_settings/channel_settings_filter.tsx
Labels: 2: QA Review

#348 [MM-18538] Add ability to name a subscription.
  server/http_test.go
  server/subscribe.go
  webapp/src/components/modals/channel_settings/__snapshots__/edit_channel_settings.test.tsx.snap
  webapp/src/components/modals/channel_settings/edit_channel_settings.test.tsx
  webapp/src/components/modals/channel_settings/edit_channel_settings.tsx
  webapp/src/components/modals/channel_settings/select_channel_subscription.tsx
  webapp/src/types/model.ts
Labels: 2: QA Review

#344 [MM-19179] Show user their settings with `/jira settings`
  server/command.go
  server/command_test.go
  server/user.go
  server/user_test.go
Labels: 3: Reviews Complete, Help Wanted

#355 Merge master into channel subscriptions
  build/manifest/main.go
  go.mod
  go.sum
  plugin.json
  server/client.go
  server/command.go
  server/command_test.go
  server/issue.go
  server/issue_parser.go
  server/manifest.go
  server/testdata/webhook-cloud-comment-deleted.json
  server/user.go
  server/user_test.go
  server/webhook.go
  server/webhook_http_test.go
  server/webhook_jira.go
  server/webhook_parser.go
  webapp/src/components/jira_issue_selector/jira_issue_selector.jsx
  webapp/src/components/modals/channel_settings/edit_channel_settings.tsx
  webapp/src/components/modals/create_issue/create_issue.jsx
  webapp/src/components/react_select_setting.jsx
  webapp/src/index.ts
  webapp/src/manifest.js
  webapp/src/manifest.ts
  webapp/src/plugin.tsx
  webapp/src/plugin_id.ts
Labels: 3: Reviews Complete

#358 [MM-19589] Update the Jira plugin for Go 1.13
  go.mod
  go.sum
Labels: 3: Reviews Complete

#354 [MM-19480] Show subscription name in delete confirmation modal
  webapp/src/components/modals/channel_settings/__snapshots__/edit_channel_settings.test.tsx.snap
  webapp/src/components/modals/channel_settings/edit_channel_settings.tsx
  webapp/src/components/modals/channel_settings/select_channel_subscription.tsx
Labels: 3: Reviews Complete

#357 [MM-18868] Server-side filtering of epic link searching
  server/http.go
  server/issue.go
  server/utils.go
  webapp/src/client/index.js
  webapp/src/components/confirm_modal.tsx
  webapp/src/components/jira_epic_selector/__snapshots__/jira_epic_selector.test.tsx.snap
  webapp/src/components/jira_epic_selector/index.ts
  webapp/src/components/jira_epic_selector/jira_epic_selector.test.tsx
  webapp/src/components/jira_epic_selector/jira_epic_selector.tsx
  webapp/src/components/modals/channel_settings/__snapshots__/edit_channel_settings.test.tsx.snap
  webapp/src/components/modals/channel_settings/channel_settings_filter.tsx
  webapp/src/components/setting.jsx
  webapp/src/types/model.ts
  webapp/src/utils/jira_issue_metadata.test.tsx
  webapp/src/utils/jira_issue_metadata.tsx
Labels: 3: Reviews Complete

#353 [MM-19073] Make labels and custom labels work correctly with subscriptions
  server/issue.go
  server/subscribe_test.go
  server/testdata/webhook-cloud-issue-created-many-fields.json
  webapp/src/components/react_select_setting.jsx
Labels: 3: Reviews Complete, Docs/Needed

#352 [MM-18536] `/jira subscribe list` command
  server/command.go
  server/subscribe.go
  server/subscribe_test.go
  webapp/src/hooks/hooks.js
Labels: 2: Dev Review

#362 [MM-19643] Limit Subscription name to 100 characters
  server/http_test.go
  server/subscribe.go
  webapp/src/components/modals/channel_settings/__snapshots__/edit_channel_settings.test.tsx.snap
  webapp/src/components/modals/channel_settings/edit_channel_settings.tsx
Labels: 3: Reviews Complete
