Repository mattermost/mattermost-plugin-jira, pull requests merged in 2019-06, with the labels that each got.

#112 [MM-15962] Allow only handled fields to show in Create Issue Dialog
  webapp/src/components/jira_field.jsx
  webapp/src/components/jira_fields.jsx
Labels: 2: Dev Review

#110 MM-15900 Improving connection flows.
  server/instance_cloud.go
  server/instance_server.go
  server/kv.go
  server/user_cloud.go
  server/user_server.go
Labels: 2: Dev Review

#117 MM-15952 Fixed GetUserInfo API incorrectly handling the "disconnected" state
  server/user.go
Labels: 2: Dev Review

#116 [MM-15880] Replaced the S3 icon used for command ephemeral posts
  server/command.go
  server/http.go
  server/plugin.go
  server/utils.go
  server/webhook.go
Labels: 3: Reviews Complete

#111 MM-15922 - Fixing theme and dropdown issue
  webapp/src/components/jira_issue_selector/jira_issue_selector.jsx
  webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx
  webapp/src/components/react_select_setting.jsx
  webapp/src/components/utils.jsx
Labels: 3: Reviews Complete

#125 - Allow fields that are not required to show up …(#112)
  webapp/src/components/jira_field.jsx
  webapp/src/components/jira_fields.jsx
Labels: 2: Dev Review

#129 [MM-15932] In Jira Connect approval page, display a better name
  server/user_cloud.go
Labels: 3: Reviews Complete

#124 [MM-15948] Create and attach issues to DM posts by sending in teamname
  server/issue.go
  webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx
  webapp/src/components/modals/attach_comment_to_issue/index.js
  webapp/src/components/modals/create_issue/create_issue.jsx
  webapp/src/components/modals/create_issue/index.js
Labels: 3: Reviews Complete

#130 [MM-15906] Update issue description created via Mattermost-Jira plugin
  server/issue.go
Labels: 2: Dev Review

#109 MM-15249: cache the current Jira instance
  server/kv.go
  server/plugin.go
Labels: 2: Dev Review

#132 [MM-15936] Enable users to cancel their selection in select-choice dropdown fields
  webapp/src/components/jira_field.jsx
  webapp/src/components/react_select_setting.jsx
Labels: 2: Dev Review

#135 MM-15983 - Updating dropdown issue
  webapp/src/components/jira_issue_selector/jira_issue_selector.jsx
  webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx
  webapp/src/components/modals/create_issue/create_issue.jsx
  webapp/src/components/react_select_setting.jsx
Labels: 2: Dev Review

#136 [MM-15938] Prevent modal closing on clicking or keyboard escape
  webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx
  webapp/src/components/modals/create_issue/create_issue.jsx
Labels: 2: Dev Review

#139 Fixed MM-15930: canonicalize Jira URL in install
  server/command.go
  server/utils.go
  server/utils_test.go
Labels: 2: Dev Review

#118 MM-15893: Fixed Jira Server webhooks
  .gitignore
  server/testdata/webhook-server-comment-created.json
  server/testdata/webhook-server-issue-updated-comment-deleted.json
  server/testdata/webhook-server-issue-updated-comment-edited.json
  server/testdata/webhook-server-issue-updated-commented.json
  server/webhook.go
  server/webhook_markdown_test.go
  server/webhook_slack_attachment.go
Labels: 3: Reviews Complete

#138 MM-15968 Better error message on missing cookies
  server/user_cloud.go
Labels: 2: Dev Review

#134 [MM-15986] Check if user does not have permissions to create issues
  server/issue.go
  webapp/src/components/modals/create_issue/create_issue.jsx
Labels: 2: Dev Review

#137 [MM-16094] Fix for: Clicking post menu for a system message crashes the app
  webapp/src/components/jira_issue_selector/index.js
  webapp/src/components/jira_issue_selector/jira_issue_selector.jsx
  webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx
  webapp/src/components/modals/create_issue/create_issue.jsx
  webapp/src/components/post_menu_actions/attach_comment_to_issue/attach_comment_to_issue.jsx
  webapp/src/components/post_menu_actions/attach_comment_to_issue/index.js
  webapp/src/components/post_menu_actions/create_issue/create_issue.jsx
  webapp/src/components/post_menu_actions/create_issue/index.js
  webapp/src/components/react_select_setting.jsx
  webapp/src/utils/jira_issue_metadata.jsx
  webapp/src/utils/posts.jsx
  webapp/src/utils/styles.js
Labels: 2: Dev Review

#119 [MM-15913] Update UX when creating issues for projects that require additional fields
  server/issue.go
  webapp/src/components/jira_field.jsx
  webapp/src/components/jira_fields.jsx
  webapp/src/components/modals/create_issue/create_issue.jsx
Labels: 2: Dev Review

#142 [MM-16129] fixed CSRF issue for Desktop app
  server/issue.go
  webapp/src/client/index.js
  webapp/src/components/jira_issue_selector/jira_issue_selector.jsx
  webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx
  webapp/src/components/modals/create_issue/create_issue.jsx
Labels: 2: Dev Review

#141 Version bump to 2.0.1
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: 3: Reviews Complete

#143 [MM-16097] Fixing: Attach to Jira Issue fails silently when user lacks permissions
  server/issue.go
  webapp/src/client/index.js
  webapp/src/components/form_button.jsx
  webapp/src/components/input.jsx
  webapp/src/components/jira_issue_selector/jira_issue_selector.jsx
  webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx
Labels: 2: Dev Review

#144 [MM-16098] Add a plugin.json setting to allow disabling of all Jirav2 UI features
  plugin.json
  server/http.go
  server/plugin.go
  server/user.go
  webapp/src/actions/index.js
  webapp/src/plugin.jsx
Labels: 2: Dev Review

#150 MM-16110: Only use slack attachments when there is something to show …
  server/testdata/webhook-issue-created-no-description-nor-relevant-fields.json
  server/testdata/webhook-issue-created-no-description.json
  server/testdata/webhook-issue-created-no-relevant-fields.json
  server/webhook.go
  server/webhook_markdown_test.go
  server/webhook_slack_attachment.go
Labels: 2: Dev Review

#107 Jira 2.0 Docs
  README.md
Labels: 3: Reviews Complete

#151 [MM-15924] Server-side error handling for create/attach Jira issue dialogs
  server/issue.go
  webapp/src/components/modals/create_issue/create_issue.jsx
Labels: 2: Dev Review

#152 MM-16145: Serve the "bot" user icon instead of the builtin
  server/http.go
Labels: 3: Reviews Complete

#153 Bumped the plugin version to 2.0.2
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: 3: Reviews Complete

#154 [MM-16229] Implement proper client-side error handling for create/attach Jira issue dialogs
  webapp/src/components/input.jsx
  webapp/src/components/jira_field.jsx
  webapp/src/components/jira_fields.jsx
  webapp/src/components/jira_issue_selector/index.js
  webapp/src/components/jira_issue_selector/jira_issue_selector.jsx
  webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx
  webapp/src/components/modals/create_issue/create_issue.jsx
  webapp/src/components/react_select_setting.jsx
  webapp/src/components/validator.js
Labels: 2: Dev Review

#155 MM-16266: always add Reporter creating issues on Jira Server
  go.mod
  go.sum
  server/issue.go
Labels: 2: Dev Review

#158 MM-16116 Fix serching in single select dropdowns.
  webapp/src/components/jira_field.jsx
Labels: 2: Dev Review

#157 Bumped the plugin version to 2.0.3
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: 3: Reviews Complete

#162 [MM-16308] Single Select validation issue
  webapp/src/components/jira_field.jsx
  webapp/src/components/react_select_setting.jsx
Labels: 2: Dev Review

#164 [MM-16309] use a dummy root component to detect when user is logged in
  webapp/src/components/setup_ui.js
  webapp/src/plugin.jsx
Labels: 2: Dev Review

#161 MM-16098 Clarify what exactly EnableJiraUI enables
  plugin.json
Labels: 2: Dev Review

#165 Bumped the version to 2.0.4
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: 3: Reviews Complete

#166 MM-16364 Use AccountID as applicable rather than Name
  Makefile
  server/command.go
  server/instance_cloud.go
  server/instance_server.go
  server/issue.go
  server/kv.go
  server/user.go
  server/user_cloud.go
  server/user_server.go
Labels: 2: Dev Review

#169 Version bump to 2.0.5
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: 2: Dev Review

#170 Don't setupUI more than once
  webapp/src/plugin.jsx
Labels: 3: Reviews Complete

#171 Version bump to 2.0.6
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: 3: Reviews Complete

#159 Migrate README updates from jira2 to master branch
  README.md
Labels: 2: Dev Review

#160 [MM-15229] Add "/jira view <issuekey>" command
  server/command.go
  server/issue.go
  server/issue_parser.go
Labels: 2: Dev Review

#175 [MM-16124] Jira Connect slash command will generate a link when no instance is installed
  server/command.go
Labels: 2: Dev Review

#183 Cherry-pick PR #151
  server/issue.go
  webapp/src/components/jira_field.jsx
  webapp/src/components/jira_fields.jsx
  webapp/src/components/modals/create_issue/create_issue.jsx
Labels: 2: Dev Review

#181 Cherry-picked PR #134
  server/issue.go
  webapp/src/components/modals/create_issue/create_issue.jsx
Labels: 2: Dev Review

#186 [MM-16229] Implement proper client-side error handling for create/at…
  webapp/src/components/input.jsx
  webapp/src/components/jira_field.jsx
  webapp/src/components/jira_fields.jsx
  webapp/src/components/jira_issue_selector/index.js
  webapp/src/components/jira_issue_selector/jira_issue_selector.jsx
  webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx
  webapp/src/components/modals/create_issue/create_issue.jsx
  webapp/src/components/react_select_setting.jsx
  webapp/src/components/validator.js
Labels: 3: Reviews Complete

#187 Cherrypick #158: Fix serching in single select dropdowns.
  webapp/src/components/jira_field.jsx
Labels: 3: Reviews Complete

#176 [MM-15786] /jira create without an installed Jira instance throws a 500 and hangs the create modal
  webapp/src/actions/index.js
  webapp/src/hooks/hooks.js
Labels: 3: Reviews Complete

#184 MM-16265 MM-16507 - Migrate to bot accounts
  Makefile
  assets/profile.png
  go.mod
  go.sum
  plugin.json
  server/command.go
  server/http.go
  server/http_test.go
  server/plugin.go
  server/plugin_test.go
  server/settings.go
  server/subscribe.go
  server/utils.go
  server/webhook_http.go
  server/webhook_http_test.go
Labels: 3: Reviews Complete, Docs/Needed

#191 Update deps
  go.mod
  go.sum
  package-lock.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/jira_issue_selector/jira_issue_selector.jsx
  webapp/webpack.config.js
Labels: 2: Dev Review

#190 MM-16603 Fixing subscription modal.
  Makefile
  webapp/src/components/modals/channel_settings/channel_settings.jsx
  webapp/src/components/modals/channel_settings/channel_settings_internal.jsx
  webapp/src/components/modals/channel_settings/index.js
  webapp/src/components/react_select_setting.jsx
  webapp/src/utils/jira_issue_metadata.jsx
Labels: 3: Reviews Complete

#192 Move ci back to master and add automatic github release.
  .circleci/config.yml
Labels: 3: Reviews Complete

#196 [MM-16528] Currently selected options in single select list are not highlighted
  webapp/src/utils/styles.js
Labels: 1: PM Review, 3: Reviews Complete

#189 MM-16588 Normalizing the "jira instance not installed" error responses; fixed help
  server/command.go
  server/issue.go
Labels: 2: Dev Review

#194 [MM-16625] jira server sends issue_updated for a assignee change
  server/testdata/webhook-issue-updated-assigned-on-server.json
  server/webhook_http_test.go
  server/webhook_parser.go
Labels: 2: Dev Review
