Repository mattermost/mattermost-plugin-jira, pull requests merged in 2019-08, with the labels that each got.

#257 [MM-17380] Intermittent 500 errors when using create
  server/issue.go
Labels: 3: Reviews Complete

#259 MM-17268: Update display names for RolesAllowedToEditJiraSubscriptions
  plugin.json
Labels: 3: Reviews Complete

#249 [MM-17267] Require user to post "/jira view <issue-key>" to preview a Jira issue
  server/command.go
Labels: 3: Reviews Complete

#245 MM-17312 Mentions in comments only work sometimes
  server/utils.go
  server/webhook.go
  server/webhook_parser.go
Labels: 3: Reviews Complete

#264 MM-17480: removed DM notifications from legacy webhooks
  server/webhook_http.go
Labels: 3: Reviews Complete

#265 Updating version to 2.1.0.
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: 2: QA Review

#262 [MM-17467] Use only one project in the channel subscriptions modal
  webapp/src/components/modals/channel_settings/channel_settings_internal.jsx
Labels: 3: Reviews Complete

#261 [MM-17111] Improve select performance for 5000 projects
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/react_select_setting.jsx
  webapp/src/components/virtualized_list.jsx
Labels: 3: Reviews Complete

#266 MM-17389 Fixing connect on desktop app.
  webapp/src/components/post_menu_actions/attach_comment_to_issue/attach_comment_to_issue.jsx
  webapp/src/components/post_menu_actions/create_issue/create_issue.jsx
Labels: 3: Reviews Complete

#268 [MM-17134] Jira connect does not tell you if user has already been mapped
  server/command.go
  server/user.go
Labels: 3: Reviews Complete

#267 Move templates into assets/
  Makefile
  assets/templates/ac/atlassian-connect.json
  assets/templates/ac/user_confirm.html
  assets/templates/ac/user_connected.html
  assets/templates/ac/user_disconnected.html
  assets/templates/ac/user_redirect.html
  assets/templates/oauth1/complete.html
  assets/templates/other/message.html
  server/plugin.go
Labels: 3: Reviews Complete

#273 Edit `/jira view` help text
  server/command.go
Labels: 3: Reviews Complete

#270 Introduce `/jira subscribe` command to open channel subscriptions modal
  server/command.go
  webapp/src/components/setup_ui/setup_ui.jsx
  webapp/src/hooks/hooks.js
Labels: 3: Reviews Complete

#271 [MM-17507] Fix issue where empty changelog value shows up as ~~~~
  server/testdata/webhook-issue-updated-multiple-values.json
  server/webhook_http_test.go
  server/webhook_parser.go
Labels: 3: Reviews Complete

#269 [MM-17510] Make `/jira connect` open in a popup for desktop app
  server/command.go
  webapp/src/hooks/hooks.js
Labels: 3: Reviews Complete

#274 Fixing automatic github release.
  .circleci/config.yml
Labels: 3: Reviews Complete

#255 [MM-15425] [MM-13850] Improved plugin development cycle
  Makefile
  webapp/package.json
  webapp/webpack.config.js
Labels: 2: Dev Review

#275 MM-17524 - Updating theme styles for jira
  webapp/src/utils/styles.js
Labels: 3: Reviews Complete

#279 [MM-17682] Improve error logging when issue updated event has no supported fields
  server/webhook_parser.go
Labels: 3: Reviews Complete

#281 [MM-17614] Handle error fetching project e.g. a project was deleted
  webapp/src/components/modals/channel_settings/channel_settings_internal.jsx
  webapp/src/utils/jira_issue_metadata.jsx
Labels: 1: PM Review, 2: QA Review

#278 [MM-17626] Custom field events not working on Jira Server
  server/subscribe.go
  server/subscribe_test.go
  server/testdata/webhook-cloud-issue-updated-custom-field.json
  server/testdata/webhook-issue-updated-custom-field.json
  server/testdata/webhook-issue-updated-multiple-custom-fields.json
  server/testdata/webhook-server-updated-custom-field.json
  server/webhook_jira.go
  server/webhook_parser.go
  webapp/src/components/modals/channel_settings/channel_settings_internal.jsx
  webapp/src/utils/jira_issue_metadata.jsx
Labels: 1: PM Review

#282 Remove templates related command from Makefile
  Makefile
Labels: 3: Reviews Complete

#284 [MM-17809] Include version and hash in `/jira info`
  build/manifest/main.go
  build/setup.mk
  server/command.go
  server/manifest.go
  webapp/src/manifest.js
Labels: 2: Dev Review

#283 [MM-17666] Handle desktop app connect auth issue for Jira Server Instance
  server/command.go
  server/instance.go
  server/kv.go
  server/user.go
  server/utils.go
  webapp/src/actions/index.js
  webapp/src/components/post_menu_actions/attach_comment_to_issue/attach_comment_to_issue.jsx
  webapp/src/components/post_menu_actions/attach_comment_to_issue/index.js
  webapp/src/components/post_menu_actions/create_issue/create_issue.jsx
  webapp/src/components/post_menu_actions/create_issue/index.js
  webapp/src/hooks/hooks.js
  webapp/src/reducers/index.js
  webapp/src/selectors/index.js
  webapp/src/utils/user_agent.jsx
Labels: 1: PM Review

#287 Try to parse events without issue_event_type_name
  server/manifest.go
  server/testdata/webhook-server-comment-deleted.json
  server/testdata/webhook-server-comment-updated.json
  server/testdata/webhook-server-old-issue-updated-no-event-type-assigned.json
  server/testdata/webhook-server-old-issue-updated-no-event-type-comment-deleted.json
  server/testdata/webhook-server-old-issue-updated-no-event-type-comment-edited.json
  server/testdata/webhook-server-old-issue-updated-no-event-type-commented.json
  server/testdata/webhook-server-old-issue-updated-no-event-type-edited.json
  server/webhook_http_test.go
  server/webhook_parser.go
  webapp/src/manifest.js
Labels: 2: Dev Review

#294 [MM-17681] Replace accountid with display name for comment mentions
  server/kv.go
  server/kv_mock_test.go
  server/manifest.go
  server/utils.go
  server/webhook.go
  webapp/src/manifest.js
Labels: 2: QA Review

#298 MM-17394: tune /jira assign user search
  server/command.go
  server/issue.go
Labels: 2: QA Review

#296 MM-17906: Added SiteURL to /jira info
  server/command.go
  server/instance_cloud.go
  server/instance_server.go
Labels: 3: Reviews Complete

#293 MM-17926 check /jira install URL against siteURL, error if match
  server/command.go
  server/utils.go
  server/utils_test.go
Labels: 1: PM Review
