Repository mattermost/mattermost-plugin-jira, pull requests merged in 2019-09, with the labels that each got.

#292 [MM-17840] Add strike-through for none on single change messages
  server/manifest.go
  server/webhook_http_test.go
  server/webhook_parser.go
  webapp/src/manifest.js
Labels: 3: Reviews Complete

#301 Prevent perpetual conflicts in generated manifest files
  Makefile
  build/manifest/main.go
  build/setup.mk
  server/command.go
  server/manifest.go
  server/plugin.go
  webapp/src/manifest.js
Labels: 3: Reviews Complete

#250 MM-15943 remove divider above plugin menu items
  webapp/src/components/post_menu_actions/create_issue/create_issue.jsx
Labels: 3: Reviews Complete

#303 Include missing event type name fix (#287) for patch release
  server/manifest.go
  server/testdata/webhook-server-comment-deleted.json
  server/testdata/webhook-server-comment-updated.json
  server/testdata/webhook-server-old-issue-updated-no-event-type-assigned.json
  server/testdata/webhook-server-old-issue-updated-no-event-type-comment-deleted.json
  server/testdata/webhook-server-old-issue-updated-no-event-type-comment-edited.json
  server/testdata/webhook-server-old-issue-updated-no-event-type-commented.json
  server/testdata/webhook-server-old-issue-updated-no-event-type-edited.json
  server/webhook_http_test.go
  server/webhook_parser.go
  webapp/src/manifest.js
Labels: 1: PM Review

#305 Bump version to 2.1.1 for patch release
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: 2: Dev Review

#289 [MM-16799] Introduce tests for the webapp side of the plugin
  .gitignore
  Makefile
  webapp/.gitignore
  webapp/babel.config.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/input.jsx
  webapp/src/components/jira_field.jsx
  webapp/src/components/jira_issue_selector/jira_issue_selector.jsx
  webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx
  webapp/src/components/modals/channel_settings/__snapshots__/channel_settings_internal.test.jsx.snap
  webapp/src/components/modals/channel_settings/channel_settings_internal.jsx
  webapp/src/components/modals/channel_settings/channel_settings_internal.test.jsx
  webapp/src/components/modals/create_issue/__snapshots__/create_issue.test.jsx.snap
  webapp/src/components/modals/create_issue/create_issue.jsx
  webapp/src/components/modals/create_issue/create_issue.test.jsx
  webapp/src/components/post_menu_actions/attach_comment_to_issue/attach_comment_to_issue.jsx
  webapp/src/components/react_select_setting.jsx
  webapp/src/components/validator.js
  webapp/src/testdata/channel.json
  webapp/src/testdata/cloud-get-create-issue-metadata-for-project.json
  webapp/src/testdata/cloud-get-jira-project-metadata.json
  webapp/src/testdata/server-get-create-issue-metadata-for-project.json
  webapp/src/testdata/server-get-jira-project-metadata.json
  webapp/tests/i18n_mock.json
  webapp/tests/setup.js
  webapp/webpack.config.js
Labels: 3: Reviews Complete

#299 Add info to troubleshooting area
  README.md
Labels: 2: Dev Review

#291 [MM-17839] Improve error message in subscribe modal when project was deleted
  webapp/src/components/modals/channel_settings/channel_settings_internal.jsx
  webapp/src/components/modals/channel_settings/channel_settings_internal.test.jsx
Labels: 3: Reviews Complete

#308 Added note to troubleshooting
  README.md
Labels: 2: Dev Review

#309 MM-17872: display different headline in comment created/updated
  server/webhook_parser.go
Labels: 1: PM Review, 2: Dev Review, 2: QA Review

#318 Fix react select cached options issue
  webapp/src/components/modals/channel_settings/__snapshots__/channel_settings_internal.test.jsx.snap
  webapp/src/components/modals/channel_settings/channel_settings_internal.jsx
  webapp/src/components/modals/create_issue/__snapshots__/create_issue.test.jsx.snap
  webapp/src/components/modals/create_issue/create_issue.jsx
  webapp/src/components/react_select_setting.jsx
Labels: 3: Reviews Complete

#310 [MM-18080] Channel subscription field filters
  plugin.json
  server/http_test.go
  server/issue.go
  server/set.go
  server/subscribe.go
  server/subscribe_test.go
  server/testdata/webhook-cloud-issue-created-many-fields.json
  server/testdata/webhook-server-issue-updated-many-fields.json
  server/webhook_worker.go
  webapp/.eslintrc.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/action_types/index.js
  webapp/src/actions/index.js
  webapp/src/components/input.jsx
  webapp/src/components/jira_issue_selector/jira_issue_selector.jsx
  webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx
  webapp/src/components/modals/channel_settings/__snapshots__/edit_channel_settings.test.tsx.snap
  webapp/src/components/modals/channel_settings/channel_settings.tsx
  webapp/src/components/modals/channel_settings/channel_settings_filter.tsx
  webapp/src/components/modals/channel_settings/channel_settings_filters.tsx
  webapp/src/components/modals/channel_settings/channel_settings_internal.tsx
  webapp/src/components/modals/channel_settings/channel_settings_modal.scss
  webapp/src/components/modals/channel_settings/edit_channel_settings.test.tsx
  webapp/src/components/modals/channel_settings/edit_channel_settings.tsx
  webapp/src/components/modals/channel_settings/select_channel_subscription.tsx
  webapp/src/components/modals/channel_settings/shared_props.ts
  webapp/src/components/modals/create_issue/__snapshots__/create_issue.test.jsx.snap
  webapp/src/components/modals/create_issue/create_issue.jsx
  webapp/src/components/modals/create_issue/create_issue.test.jsx
  webapp/src/components/modals/full_screen_modal/close_icon.jsx
  webapp/src/components/modals/full_screen_modal/full_screen_modal.jsx
  webapp/src/components/modals/full_screen_modal/full_screen_modal.scss
  webapp/src/components/modals/full_screen_modal/full_screen_modal.test.jsx
  webapp/src/components/react_select_setting.jsx
  webapp/src/components/setting.jsx
  webapp/src/components/validator.js
  webapp/src/components/validator.ts
  webapp/src/index.js
  webapp/src/index.ts
  webapp/src/plugin.tsx
  webapp/src/reducers/index.js
  webapp/src/selectors/index.js
  webapp/src/testdata/cloud-get-create-issue-metadata-for-project-many-fields.json
  webapp/src/types/model.ts
  webapp/src/utils/jira_issue_metadata.test.tsx
  webapp/src/utils/jira_issue_metadata.tsx
  webapp/tsconfig.json
  webapp/webpack.config.js
Labels: 3: Reviews Complete

#323 MM-17613: Fixed error message in Cloud SearchIssues
  build/manifest/main.go
  server/client.go
Labels: 3: Reviews Complete

#324 Fixed MM-18725: failure to create reply posts in threads
  server/issue.go
Labels: 3: Reviews Complete

#326 Bumped release number to 2.2
  plugin.json
  server/manifest.go
  webapp/src/manifest.ts
Labels: 3: Reviews Complete
