Repository mattermost/mattermost-plugin-jira, pull requests merged in 2019-05, with the labels that each got.

#41 Proposed text updates for /jira slash commands
  server/command.go
Labels: 2: Dev Review

#42 Some cleanup for Jira plugin
  plugin.json
  server/http.go
  server/instance_cloud.go
  server/instance_server.go
  server/kv.go
  server/message_posted.go
  server/templates/atlassian-connect.json
  server/user.go
  server/user_atlassian_connect.go
  server/user_oauth1.go
  server/utils.go
  server/webhook.go
  webapp/src/components/post_menu_actions/create_issue/create_issue.jsx
Labels: 2: Dev Review

#39 MM-15244 Jira Cloud user connect security
  server/atlassian_connect.go
  server/auth_token.go
  server/command.go
  server/http.go
  server/instance.go
  server/instance_cloud.go
  server/instance_server.go
  server/issue.go
  server/kv.go
  server/plugin.go
  server/templates/ac/atlassian-connect.json
  server/templates/ac/user_confirm.html
  server/templates/ac/user_connected.html
  server/templates/ac/user_disconnected.html
  server/templates/ac/user_redirect.html
  server/templates/oauth1/complete.html
  server/user.go
  server/user_atlassian_connect.go
  server/user_cloud.go
  server/user_server.go
Labels: 3: Reviews Complete

#40 Doc updates for roadmap and Jira Server install docs
  README.md
Labels: 2: Dev Review

#46 MM-15101 Adding /jira transition
  server/command.go
  server/issue.go
Labels: 3: Reviews Complete

#44 MM-15253 Refactor of create-issue modal.
  Makefile
  webapp/package-lock.json
  webapp/package.json
  webapp/src/action_types/create_issue.js
  webapp/src/action_types/index.js
  webapp/src/actions/index.js
  webapp/src/components/form_button.jsx
  webapp/src/components/input.jsx
  webapp/src/components/jira_field.jsx
  webapp/src/components/jira_fields.jsx
  webapp/src/components/modals/create_issue/create_issue.jsx
  webapp/src/components/modals/create_issue/index.js
  webapp/src/components/react_select_setting.jsx
  webapp/src/components/setting.jsx
  webapp/src/components/settings/dropdown.jsx
  webapp/src/components/settings/multiselect.jsx
  webapp/src/jira_issue_metadata.jsx
  webapp/src/reducers/index.js
  webapp/src/selectors/index.js
  webapp/webpack.config.js
Labels: 2: Dev Review

#45 Fixed /jira subcommand parsing consistency
  server/command.go
Labels: 2: Dev Review

#50 Fixed creating server/dist/templates/templates on a 2nd make
  Makefile
Labels: 2: Dev Review

#52 small fixes to /jira instance delete
  server/command.go
Labels: 3: Reviews Complete

#55 MM-15455 Some improvments to cloud connect flow.
  server/instance_cloud.go
  server/user.go
  server/user_cloud.go
Labels: 2: Dev Review

#54 MM-15096 UI fixes for template pages and menu item
  server/templates/ac/user_confirm.html
  server/templates/ac/user_connected.html
  server/templates/ac/user_disconnected.html
  server/templates/oauth1/complete.html
  webapp/src/components/post_menu_actions/create_issue/create_issue.jsx
Labels: 1: PM Review

#48 Update Jira application link for Cloud
  README.md
Labels: 2: Dev Review

#53 Fixed a bug in unescaping webhook secret
  server/command.go
  server/instance_server.go
  server/webhook.go
Labels: 3: Reviews Complete

#47 MM-15400 Added some protections to /installed link
  server/atlassian_connect.go
  server/command.go
  server/instance_cloud.go
  server/issue.go
  server/kv.go
Labels: 1: PM Review, 2: Dev Review

#59 Added response logging for Jira API errors
  server/issue.go
Labels: 2: Dev Review

#57 [MM-14773] [MM-15440] - simplify settings and setup
  plugin.json
  server/command.go
  server/plugin.go
Labels: 3: Reviews Complete

#58 Remove periods from titles
  server/command.go
  server/templates/ac/user_confirm.html
  server/templates/ac/user_connected.html
  server/templates/oauth1/complete.html
Labels: 3: Reviews Complete

#56 [MM-14513] Implement attaching messages to Jira issues as comment
  server/http.go
  server/issue.go
  server/message_posted.go
  webapp/src/action_types/index.js
  webapp/src/actions/index.js
  webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx
  webapp/src/components/modals/attach_comment_to_issue/index.js
  webapp/src/components/post_menu_actions/attach_comment_to_issue/JiraIcon.png
  webapp/src/components/post_menu_actions/attach_comment_to_issue/attach_comment_to_issue.jsx
  webapp/src/components/post_menu_actions/attach_comment_to_issue/index.js
  webapp/src/components/post_menu_actions/create_issue/JiraIcon.png
  webapp/src/plugin.jsx
  webapp/src/reducers/index.js
  webapp/src/selectors/index.js
Labels: 3: Reviews Complete

#63 Update few texts in post menu and Attach/Create Jira issue screens
  webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx
  webapp/src/components/modals/create_issue/create_issue.jsx
  webapp/src/components/post_menu_actions/attach_comment_to_issue/attach_comment_to_issue.jsx
Labels: 3: Reviews Complete

#67 [MM-15533] Change ephemeral message to <issue-key> transitioned to <state>
  server/command.go
  server/issue.go
Labels: 3: Reviews Complete

#68 Update timeline and feature set for v2.0/v2.1
  README.md
Labels: 2: Dev Review

#61 MM-15462 Basic subscribe to jira events.
  Makefile
  server/http.go
  server/http_test.go
  server/subscribe.go
  server/webhook.go
  webapp/src/action_types/index.js
  webapp/src/actions/index.js
  webapp/src/components/icon.jsx
  webapp/src/components/jira_field.jsx
  webapp/src/components/jira_fields.jsx
  webapp/src/components/modals/channel_settings/channel_settings.jsx
  webapp/src/components/modals/channel_settings/channel_settings_internal.jsx
  webapp/src/components/modals/channel_settings/index.js
  webapp/src/components/post_menu_actions/create_issue/create_issue.jsx
  webapp/src/components/react_select_setting.jsx
  webapp/src/jira_issue_metadata.jsx
  webapp/src/plugin.jsx
  webapp/src/reducers/index.js
  webapp/src/selectors/index.js
Labels: 3: Reviews Complete

#51 [MM-15411] /jira create command
  server/command.go
  server/issue.go
  webapp/src/action_types/index.js
  webapp/src/actions/index.js
  webapp/src/components/modals/create_issue/create_issue.jsx
  webapp/src/components/modals/create_issue/index.js
  webapp/src/hooks/hooks.js
  webapp/src/plugin.jsx
  webapp/src/reducers/index.js
  webapp/src/selectors/index.js
Labels: 2: Dev Review

#65 [ MM-15015] Add jira Icons to create and attach post menu items
  webapp/src/components/icon.jsx
  webapp/src/components/post_menu_actions/attach_comment_to_issue/JiraIcon.png
  webapp/src/components/post_menu_actions/attach_comment_to_issue/attach_comment_to_issue.jsx
  webapp/src/components/post_menu_actions/create_issue/JiraIcon.png
  webapp/src/components/post_menu_actions/create_issue/create_issue.jsx
  webapp/webpack.config.js
Labels: 2: Dev Review

#62 [MM 15099] direct message notifications on off
  server/command.go
  server/settings.go
  server/subscribe.go
  server/testdata/webhook-comment-created.json
  server/testdata/webhook-comment-deleted.json
  server/testdata/webhook-comment-updated.json
  server/testdata/webhook-issue-updated-assigned-nobody.json
  server/testdata/webhook-issue-updated-assigned.json
  server/testdata/webhook-issue-updated-attachments.json
  server/testdata/webhook-issue-updated-edited.json
  server/testdata/webhook-issue-updated-labels.json
  server/testdata/webhook-issue-updated-lowered-priority.json
  server/testdata/webhook-issue-updated-raised-priority.json
  server/testdata/webhook-issue-updated-rank.json
  server/testdata/webhook-issue-updated-renamed.json
  server/testdata/webhook-issue-updated-reopened.json
  server/testdata/webhook-issue-updated-resolved.json
  server/testdata/webhook-issue-updated-sprint.json
  server/testdata/webhook-issue-updated-started-working.json
  server/user.go
  server/user_cloud.go
  server/user_server.go
  server/utils.go
  server/webhook.go
  server/webhook_slack_attachment.go
Labels: 2: Dev Review

#71 MM-15535 - UI updates for Jira 2
  webapp/src/components/input.jsx
  webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx
  webapp/src/components/modals/create_issue/create_issue.jsx
  webapp/src/components/setting.jsx
Labels: 3: Reviews Complete

#72 MM-15439 Restores 1.0 compatibility for webhook filtering
  server/utils.go
  server/webhook.go
  server/webhook_markdown.go
  server/webhook_markdown_test.go
  server/webhook_slack_attachment.go
  server/webhook_slack_attachment_test.go
Labels: 2: Dev Review

#77 Minor modifications to "/jira help" text
  server/command.go
Labels: 3: Reviews Complete

#76 Update user_disconnected.html
  server/templates/ac/user_disconnected.html
Labels: 3: Reviews Complete

#80 * give correct URL in /jira install server instructions
  server/command.go
Labels: 3: Reviews Complete

#83 Minor modifications to "/jira help" text (#77)
  server/command.go
Labels: 3: Reviews Complete

#93 MM-15866: Webhook presentation tweaks in jira2
  server/webhook.go
  server/webhook_markdown_test.go
  server/webhook_slack_attachment.go
  server/webhook_slack_attachment_test.go
Labels: 2: Dev Review

#74 [MM-15015] cherry-pick #65 from jira2 ...icons to ... menu items
  webapp/src/components/icon.jsx
  webapp/src/components/post_menu_actions/attach_comment_to_issue/JiraIcon.png
  webapp/src/components/post_menu_actions/attach_comment_to_issue/attach_comment_to_issue.jsx
  webapp/src/components/post_menu_actions/create_issue/JiraIcon.png
  webapp/src/components/post_menu_actions/create_issue/create_issue.jsx
  webapp/webpack.config.js
Labels: 2: Dev Review

#66 [MM-15536/MM-15832] Only show one "Connect to Jira" menu option.
  webapp/src/components/post_menu_actions/attach_comment_to_issue/attach_comment_to_issue.jsx
  webapp/src/components/post_menu_actions/attach_comment_to_issue/index.js
  webapp/src/components/post_menu_actions/create_issue/create_issue.jsx
  webapp/src/components/post_menu_actions/create_issue/index.js
  webapp/src/selectors/index.js
Labels: 2: Dev Review

#94 [MM-15762] detect if the post is a reply and send the correct fields
  server/issue.go
Labels: 2: Dev Review

#75 [MM-15537] Fix 'connect to jira' menu item when not connected
  server/atlassian_connect.go
  server/command.go
  server/http.go
  server/instance.go
  server/instance_cloud.go
  server/kv.go
  server/user.go
  webapp/src/action_types/index.js
  webapp/src/actions/index.js
  webapp/src/components/post_menu_actions/attach_comment_to_issue/attach_comment_to_issue.jsx
  webapp/src/components/post_menu_actions/attach_comment_to_issue/index.js
  webapp/src/components/post_menu_actions/create_issue/create_issue.jsx
  webapp/src/components/post_menu_actions/create_issue/index.js
  webapp/src/plugin.jsx
  webapp/src/reducers/index.js
  webapp/src/selectors/index.js
Labels: 3: Reviews Complete

#97 Webhooks - Jira cloud old view assignee
  server/webhook.go
Labels: 3: Reviews Complete

#81 [MM-15589] Create Issue: (Jira server) Priority field fails to select
  webapp/src/components/jira_field.jsx
  webapp/src/components/jira_fields.jsx
  webapp/src/components/modals/create_issue/create_issue.jsx
Labels: 3: Reviews Complete

#78 MM-15733 - Making react select theme compatible
  webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx
  webapp/src/components/modals/create_issue/create_issue.jsx
  webapp/src/components/react_select_setting.jsx
Labels: 2: Dev Review

#95 [MM-15658] Fix for description not editable on server instances
  webapp/src/components/input.jsx
  webapp/src/components/jira_field.jsx
  webapp/src/components/jira_fields.jsx
Labels: 2: Dev Review

#100 [MM-15537] Fix 'connect to jira' menu item when not connected (#75)
  server/atlassian_connect.go
  server/command.go
  server/http.go
  server/instance.go
  server/instance_cloud.go
  server/kv.go
  server/user.go
  webapp/src/action_types/index.js
  webapp/src/actions/index.js
  webapp/src/components/post_menu_actions/attach_comment_to_issue/attach_comment_to_issue.jsx
  webapp/src/components/post_menu_actions/attach_comment_to_issue/index.js
  webapp/src/components/post_menu_actions/create_issue/create_issue.jsx
  webapp/src/components/post_menu_actions/create_issue/index.js
  webapp/src/plugin.jsx
  webapp/src/reducers/index.js
  webapp/src/selectors/index.js
Labels: 2: Dev Review

#103 Allow all Jira Fields to show up in create-issue dialog
  webapp/src/components/jira_fields.jsx
Labels: 2: Dev Review

#104 Mm 15733 fix to theme pr
  webapp/src/components/jira_field.jsx
  webapp/src/components/jira_fields.jsx
  webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx
  webapp/src/components/modals/create_issue/create_issue.jsx
  webapp/src/components/react_select_setting.jsx
Labels: 2: Dev Review

#108 [MM- 15838] Handle selected elements in Jira issue creation screen
  webapp/src/components/jira_field.jsx
Labels: 2: Dev Review

#101 [MM-15286] Improve the /jira disconnect user experience
  server/command.go
  server/user.go
Labels: 3: Reviews Complete

#82 MM-15439 refactor and merge webhooks #72 from jira2
  .gitignore
  go.mod
  go.sum
  server/atlassian_connect.go
  server/auth_token.go
  server/command.go
  server/http.go
  server/instance.go
  server/instance_cloud.go
  server/instance_server.go
  server/issue.go
  server/kv.go
  server/kv_mock_test.go
  server/plugin.go
  server/plugin_test.go
  server/settings.go
  server/subscribe.go
  server/user.go
  server/user_cloud.go
  server/user_server.go
  server/utils.go
  server/webhook.go
  server/webhook_http.go
  server/webhook_http_test.go
  server/webhook_jira.go
  server/webhook_markdown.go
  server/webhook_markdown_test.go
  server/webhook_parser.go
  server/webhook_parser_misc_test.go
  server/webhook_slack_attachment.go
  server/webhook_slack_attachment_test.go
Labels: 2: Dev Review

#79 [MM-15677] autocomplete for issue keys in Attach to Jira Issue
  .gitignore
  server/http.go
  server/issue.go
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/form_button.jsx
  webapp/src/components/jira_issue_selector/index.js
  webapp/src/components/jira_issue_selector/jira_issue_selector.jsx
  webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx
  webapp/src/components/modals/attach_comment_to_issue/index.js
  webapp/src/reducers/index.js
Labels: 2: Dev Review
