Repository mattermost/mattermost-plugin-jira, pull requests merged in 2020-08, with the labels that each got.

#554 GH-531 Add info about /jira webhook
  plugin.json
  server/command.go
  server/command_test.go
Labels: 4: Reviews Complete

#598 Avoid double slash in webapp API calls when SiteURL is not present
  webapp/src/selectors/index.js
Labels: 4: Reviews Complete

#595 Remove unnecessary refs
  webapp/src/components/confirm_modal.tsx
  webapp/src/components/jira_issue_selector/index.js
  webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx
  webapp/src/components/modals/create_issue/create_issue.jsx
Labels: 4: Reviews Complete

#625 Cherrypick "Make it so subscribe autocomplete shows for all users"
  server/command.go
Labels: 2: Dev Review, 3: QA Review

#623 [GH-612] Add ability to change telemetry key to production key on release builds
  Makefile
  build/custom.mk
  server/utils/telemetry/rudder.go
Labels: 4: Reviews Complete

#637 Check for nil diagnostic setting
  server/plugin.go
Labels: 4: Reviews Complete

#639 Close modal on missing required fields
  webapp/src/components/modals/create_issue/create_issue_form.tsx
Labels: 4: Reviews Complete

#635 Bump version to v3.0.0-beta2
  plugin.json
  server/manifest.go
  webapp/src/manifest.ts
Labels: 4: Reviews Complete

#643 Bump version to v3.0.0-beta2.1
  plugin.json
  server/manifest.go
  webapp/src/manifest.ts
Labels: 4: Reviews Complete, QA Review Done

#627 Update readme.md
  readme.md
Labels: Work In Progress

#644 Update README.md
  docs/README.md
Labels: 1: PM Review
