Repository mattermost/mattermost-plugin-jira, pull requests merged in 2020-03, with the labels that each got.

#480 MM-22063 Adding create ticket action support for workflow.
  go.mod
  go.sum
  server/http.go
  server/instance_cloud.go
  server/issue.go
  server/plugin.go
Labels: 3: Reviews Complete, QA Review Done

#459 MM-18075 Reuse output of `/jira view` in the output of `/jira create`
  server/issue.go
Labels: 3: Reviews Complete, QA Review Done

#482 Fix dead link
  .gitignore
  plugin.json
Labels: QA Review Done

#469 [GH-145] Add link to ephemeral message after uninstall
  server/command.go
  server/command_test.go
  server/instance.go
  server/instance_cloud.go
  server/instance_server.go
  server/kv_mock_test.go
Labels: 3: Reviews Complete, QA Review Done

#478 Add Site URL to third-party cookie error message
  server/user_cloud.go
Labels: 3: Reviews Complete, QA Review Done

#503 MM-21696: New config setting: Hide issue descriptions and comments
  plugin.json
  server/plugin.go
  server/webhook.go
Labels: 3: Reviews Complete, AutoMerge, QA Review Done

#454 [MM-17816] Add the ability to transition an issue after running `/jira view`
  server/http.go
  server/issue.go
  server/issue_parser.go
  server/issue_test.go
Labels: 3: Reviews Complete, Lifecycle/1:stale, QA Review Done

#508 Fix test under go 1.14
  server/utils/utils_test.go
Labels: 3: Reviews Complete

#500 MM-19674: use respondXXX in http handlers
  server/atlassian_connect.go
  server/http.go
  server/instance.go
  server/instance_cloud.go
  server/instance_server.go
  server/issue.go
  server/stats.go
  server/subscribe.go
  server/user.go
  server/user_cloud.go
  server/user_server.go
  server/webhook_http.go
Labels: 3: Reviews Complete, QA Review Done
