Repository mattermost/mattermost-plugin-jira, pull requests merged in 2020-02, with the labels that each got.

#457 [MM-20744] Use FullScreenModal--compact css class, defined by mattermost-webapp
  webapp/src/components/modals/full_screen_modal/full_screen_modal.jsx
  webapp/src/components/modals/full_screen_modal/full_screen_modal.scss
  webapp/src/components/modals/full_screen_modal/full_screen_modal.test.jsx
Labels: 3: Reviews Complete, QA Review Done

#460 Add unassign slash command
  server/command.go
  server/issue.go
Labels: 3: Reviews Complete, QA Review Done

#453 MM-17818 Adding automatic registration of autolinks for JIRA projects.
  go.mod
  go.sum
  server/atlassian_connect.go
  server/client.go
  server/plugin.go
Labels: 1: PM Review

#450 MM-21303 Workflow plugin integration.
  go.mod
  go.sum
  server/command.go
  server/http.go
  server/plugin.go
  server/subscribe.go
  server/subscribe_test.go
  server/webhook_jira.go
  server/webhook_worker.go
  server/workflow.go
Labels: 3: Reviews Complete, QA Review Done

#466 When posting a response from the Jira plugin, we get React warnings in the console
  webapp/src/components/modals/create_issue/create_issue.jsx
Labels: 2: Dev Review, 2: QA Review

#462 [MM-17816] Reporter is not automatically set for `/jira create` on Jira Server, when required field is missing
  server/client.go
Labels: 3: Reviews Complete, QA Review Done

#474 Generate a proper webhook URL
  server/webhook.go
Labels: 3: Reviews Complete, QA Review Done

#467 [GH-167] Render JIRA webhook comments as quoted messages
  server/webhook_http_test.go
  server/webhook_parser.go
  server/webhook_parser_misc_test.go
Labels: 3: Reviews Complete, QA Review Done

#464 Created/Attached to a Jira issue message should include a reference to the Jira plugin
  server/command_test.go
  server/http.go
  server/issue.go
  server/issue_test.go
  server/kv_mock_test.go
  server/plugin.go
  server/user.go
  server/user_test.go
Labels: 3: Reviews Complete, QA Review Done
