Repository mattermost/mattermost-plugin-jira, pull requests merged in 2020-09, with the labels that each got.

#632 Improve disconnect message when user is not connected to any instances
  server/command.go
Labels: 4: Reviews Complete

#653 Add Autocomplete icon
  go.mod
  go.sum
  server/command.go
  server/command_test.go
  server/instances_test.go
Labels: 4: Reviews Complete

#650 Avoid defaultUserInstanceID reducer error
  webapp/src/reducers/index.js
Labels: 4: Reviews Complete

#621 Delay opening subscribe modal until we know the user has permissions
  webapp/src/components/modals/channel_settings/channel_settings.test.tsx
  webapp/src/components/modals/channel_settings/channel_settings.tsx
  webapp/src/components/modals/channel_settings/channel_settings_internal.tsx
Labels: 4: Reviews Complete

#633 Include chrome-specific error message in third-party cookie connect error
  server/user_cloud.go
Labels: 4: Reviews Complete

#655 [GH-645] update text to mention groups only work for legacy instance
  plugin.json
Labels: 2: Dev Review, QA Review Done

#648 Update feature-summary.md
  docs/feature-summary.md
Labels: 4: Reviews Complete

#629 Implement `/jira v2revert`
  server/command.go
  server/jiraTracker/tracker.go
  server/kv.go
  server/kv_migrate_test.go
Labels: QA Review Done

#651 2.3 doc review and updates
  docs/README.md
  docs/SUMMARY.md
  docs/admininstrator-guide/notification-management.md
  docs/admininstrator-guide/permissions.md
  docs/admininstrator-guide/troubleshooting.md
  docs/administrator-guide/frequently-asked-questions-faq.md
  docs/development/environment.md
  docs/end-user-guide/getting-started.md
  docs/end-user-guide/using-jira-commands.md
  docs/setup/configuration.md
  docs/setup/updating-the-plugin.md
Labels: 1: PM Review

#667 [GH-526] make server install help text more clear to the user.
  assets/templates/command/install_server.md
Labels: 4: Reviews Complete, QA Review Done

#666 [GH-663] Saved subscription project value incorrectly updated to default_project_key value
  webapp/src/components/jira_instance_and_project_selector/jira_instance_and_project_selector.tsx
Labels: 4: Reviews Complete

#662 Add release_notes_url
  plugin.json
Labels: 4: Reviews Complete
