Repository mattermost/mattermost-plugin-jira, pull requests merged in 2020-05, with the labels that each got.

#534 Refactor plugin key generation code
  server/plugin.go
Labels: 4: Reviews Complete, QA Review Done

#546 Fixed a nil pointer check
  server/client.go
Labels: 3: QA Review

#530 Bump version to 2.4.0
  plugin.json
  server/manifest.go
  webapp/src/manifest.ts
Labels: 4: Reviews Complete, QA Review Done

#536 [MM-24699] fix spinner
  webapp/src/components/form_button.jsx
Labels: 4: Reviews Complete

#550 Add badges to README
  readme.md
Labels: 4: Reviews Complete

#553 change link to documentation
  server/command.go
  webapp/package-lock.json
Labels: 4: Reviews Complete
