Repository mattermost/mattermost-plugin-jira, pull requests merged in 2020-04, with the labels that each got.

#518 Add CODEOWNERS and maintainers
  CODEOWNERS
  readme.md
Labels: 3: Reviews Complete

#513 rename `respondErr` function
  server/issue.go
  server/issue_test.go
Labels: 3: Reviews Complete, QA Review Done

#521 npm -E audit fix in prep for 2.4 release
  webapp/package-lock.json
  webapp/package.json
Labels: 3: Reviews Complete

#516 Add docker-compose.yml to spin up Jira Server instance
  docker-compose.yml
  readme.md
Labels: 2: Dev Review, 2: QA Review

#528 Drop second maintainer from CODEOWNERS
  CODEOWNERS
Labels: 3: Reviews Complete

#517 [GH-506] Correctly link or embed attachments
  server/client.go
  server/issue.go
  server/utils.go
Labels: 3: Reviews Complete, QA Review Done

#525 [MM-485] - Update `commonHelpText` and `sysAdminHelpText` to include all slash commands
  server/command.go
Labels: 3: Reviews Complete, QA Review Done

#523 [GH-490] Fix connect link on /jira info output
  server/command.go
Labels: 3: Reviews Complete, QA Review Done
