Repository mattermost/mattermost-plugin-jira, pull requests merged in 2020-01, with the labels that each got.

#419 GH-392: Allow system admins to provide a block of text to display in output of `/jira help`
  plugin.json
  server/command.go
  server/plugin.go
Labels: 3: Reviews Complete

#434 Bump Mattermost to 5.18
  build/manifest/main.go
  go.mod
  go.sum
  server/client.go
  server/command.go
  server/command_test.go
  server/http.go
  server/http_test.go
  server/issue.go
  server/issue_parser.go
  server/kv.go
  server/main.go
  server/plugin.go
  server/plugin_test.go
  server/settings.go
  server/stats_test.go
  server/subscribe.go
  server/subscribe_test.go
  server/user.go
  server/user_cloud.go
  server/user_server.go
  server/utils.go
  server/webhook.go
  server/webhook_http_test.go
  server/webhook_parser.go
Labels: 3: Reviews Complete

#433 Bumped version to v2.3.2
  plugin.json
  server/manifest.go
  webapp/src/manifest.ts
Labels: 3: Reviews Complete

#436 [MM-21218] Display placeholder text when a channel has no subscriptions
  webapp/src/components/modals/channel_settings/select_channel_subscription.tsx
Labels: 3: Reviews Complete

#437 MM-16948 Check if Jira server url actually is a Jira Cloud URL
  server/command.go
  server/command_test.go
  server/utils/utils.go
  server/utils/utils_test.go
Labels: 3: Reviews Complete

#445 Add jest watch command
  webapp/package.json
Labels: 3: Reviews Complete

#446 Fix help text test
  server/command_test.go
Labels: 3: Reviews Complete

#448 Remove the ji arg of type Instance from UserStore interface method CountUsers
  server/kv.go
  server/kv_mock_test.go
  server/stats.go
Labels: 2: Dev Review, 3: Reviews Complete

#443 [MM-20281] Show channel name at the top of subscription modal when editing a subscription
  webapp/src/components/modals/channel_settings/__snapshots__/edit_channel_settings.test.tsx.snap
  webapp/src/components/modals/channel_settings/edit_channel_settings.tsx
Labels: 3: Reviews Complete

#432 [MM-17903] Validate form for subscription create/edit
  server/http_test.go
  server/issue_test.go
  server/subscribe.go
Labels: 3: Reviews Complete

#455 Add more manifest metadata
  assets/icon.svg
  plugin.json
Labels: 3: Reviews Complete

#456 bump go version from 1.12 to 1.13
  go.mod
Labels: 3: Reviews Complete

#442 [MM-21762] Refactor jira issue search
  server/http.go
  server/issue.go
  webapp/src/actions/index.js
  webapp/src/components/jira_epic_selector/__snapshots__/jira_epic_selector.test.tsx.snap
  webapp/src/components/jira_epic_selector/index.ts
  webapp/src/components/jira_epic_selector/jira_epic_selector.test.tsx
  webapp/src/components/jira_epic_selector/jira_epic_selector.tsx
  webapp/src/components/jira_issue_selector/index.js
  webapp/src/components/jira_issue_selector/jira_issue_selector.jsx
  webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx
Labels: 3: Reviews Complete, QA Review Done

#451 [MM-20280] Display reporter name and avatar in `/jira view` output
  server/issue_parser.go
Labels: 3: Reviews Complete

#458 Fixes MM-18737 : Change wording of save subscription buttons
  webapp/src/components/modals/channel_settings/__snapshots__/edit_channel_settings.test.tsx.snap
  webapp/src/components/modals/channel_settings/channel_settings_internal.tsx
  webapp/src/components/modals/channel_settings/edit_channel_settings.test.tsx
  webapp/src/components/modals/channel_settings/edit_channel_settings.tsx
Labels: 3: Reviews Complete, QA Review Done
