Repository mattermost/mattermost-plugin-jira, pull requests merged in 2020-10, with the labels that each got.

#677 [GH-672] add additional pipe for v2legacy print lines
  server/command.go
Labels: 4: Reviews Complete, QA Review Done

#680 [GH-678] when using --instance, show alias if available else show the instanceID
  server/command.go
  server/instances.go
Labels: 4: Reviews Complete, QA Review Done

#681 Bump min server version to v5.26.0
  plugin.json
Labels: 4: Reviews Complete

#669 [GH-622] Bump version to v3.0.0
  plugin.json
  server/manifest.go
  webapp/src/manifest.ts
Labels: 4: Reviews Complete

#689 Fix typo in help command
  server/command.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#692 Updates for Jira 3.0
  docs/README.md
  docs/SUMMARY.md
  docs/admininstrator-guide/administrator-slash-commands.md
  docs/end-user-guide/faq.md
  docs/end-user-guide/using-jira-commands.md
  docs/setup/configuration.md
  docs/setup/installation.md
Labels: 4: Reviews Complete

#695 Update readme.md
  readme.md
Labels: 2: Dev Review

#696 Update README.md
  docs/README.md
Labels: 4: Reviews Complete

#687 [GH-589] Change log level for autolink when no cloud instance
  server/plugin.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#684 Post command response in RHS if triggered from there
  server/command.go
Labels: 4: Reviews Complete

#697 Relocate dev docs to GitBook
  docs/admininstrator-guide/notification-management.md
  docs/development/environment.md
  readme.md
Labels: 1: PM Review

#703 Update environment.md
  docs/development/environment.md
Labels: 1: PM Review, 2: Dev Review

#671 Add return empty Instances in store.LoadInstances if not found
  server/kv.go
Labels: 4: Reviews Complete

#686 [GB-624] Check autolink status before use
  server/plugin.go
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#709 [GH-708] Fix check for autolink plug-in errors
  server/plugin.go
Labels: Hacktoberfest, hacktoberfest-accepted

#702 Update help-and-support.md
  docs/help-and-support.md
Labels: 1: PM Review, 2: Dev Review
