Repository mattermost/mattermost-plugin-jira, pull requests merged in 2021-04, with the labels that each got.

#753 Clarify Enterprise required for multiple instances
  readme.md
Labels: 1: UX Review

#763 Update code maintainers
  CODEOWNERS
  readme.md
Labels: 4: Reviews Complete

#754 Jira docs 3.0 channel subscriptions edits
  docs/.gitbook/assets/channel-subscriptions-modal.png
  docs/admininstrator-guide/administrator-slash-commands.md
  docs/admininstrator-guide/notification-management.md
  docs/administrator-guide/frequently-asked-questions-faq.md
  docs/end-user-guide/notification-subscriptions.md
  docs/setup/configuration.md
  go.sum
Labels: 1: PM Review, AutoMerge

#739 Jira docs 3.0
  docs/.gitbook/assets/channel-subscriptions-modal.png
  docs/.gitbook/assets/jira-commands.png
  docs/SUMMARY.md
  docs/administrator-guide/administrator-slash-commands.md
  docs/administrator-guide/frequently-asked-questions-faq.md
  docs/administrator-guide/notification-management.md
  docs/end-user-guide/getting-started.md
  docs/end-user-guide/notification-subscriptions.md
  docs/setup/configuration.md
  readme.md
Labels: 4: Reviews Complete
