Repository mattermost/mattermost-plugin-jira, pull requests merged in 2021-09, with the labels that each got.

#784 Update SUMMARY.md (TOC file)
  docs/SUMMARY.md
Labels: 2: Dev Review

#800 Bump to version 3.1.0
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: 4: Reviews Complete

#780 Separate UI-related end-user docs from commands section
  docs/end-user-guide/interacting-with-forms.md
  docs/end-user-guide/using-jira-commands.md
Labels: 2: Dev Review

#809 updated error message
  server/plugin.go
Labels: 4: Reviews Complete, Contributor

#807 Add back build info
  build/custom.mk
Labels: 4: Reviews Complete
