Repository mattermost/mattermost-plugin-jira, pull requests merged in 2021-02, with the labels that each got.

#712 [GH-658] Add golang-ci lint
  .golangci.yml
  Makefile
  build/deploy/main.go
  build/manifest/main.go
  build/setup.mk
  go.mod
  go.sum
  server/atlassian_connect.go
  server/auth_token.go
  server/client.go
  server/command.go
  server/command_test.go
  server/enterprise/license.go
  server/event_types.go
  server/expvar/endpoint.go
  server/expvar/endpoint_test.go
  server/expvar/stats_test.go
  server/http.go
  server/http_test.go
  server/info.go
  server/instance.go
  server/instance_cloud.go
  server/instance_server.go
  server/instances.go
  server/instances_test.go
  server/issue.go
  server/issue_parser.go
  server/issue_test.go
  server/jira_test_util_test.go
  server/kv.go
  server/kv_migrate_test.go
  server/kv_mock_test.go
  server/manifest.go
  server/plugin.go
  server/settings.go
  server/stats.go
  server/subscribe.go
  server/subscribe_test.go
  server/tracker/tracker.go
  server/user.go
  server/user_cloud.go
  server/user_server.go
  server/utils.go
  server/utils/byte_size.go
  server/utils/kvstore/entity.go
  server/utils/kvstore/hashed_key.go
  server/utils/kvstore/id_index.go
  server/utils/telemetry/tracker.go
  server/utils/types/byte_size.go
  server/utils/utils.go
  server/webhook.go
  server/webhook_http.go
  server/webhook_http_test.go
  server/webhook_jira.go
  server/webhook_parser.go
  server/webhook_parser_misc_test.go
  server/webhook_worker.go
  server/workflow.go
  webapp/src/manifest.js
Labels: 4: Reviews Complete

#737 Update SUMMARY.md
  docs/SUMMARY.md
Labels: 2: Dev Review

#736 [Fix: #657] : Drop Fetching subscriptions ephemeral post
  webapp/src/components/modals/channel_subscriptions/channel_subscriptions.tsx
Labels: 4: Reviews Complete

#717 Clarify requirement of e20 license for multiple connected Jira server
  docs/README.md
Labels: 2: Dev Review

#735 Release 3.0.1 updates
  server/command.go
  server/info.go
  server/instance.go
  server/instance_cloud.go
  server/instance_server.go
  server/instances.go
  server/kv_mock_test.go
  server/user.go
  server/user_cloud.go
Labels: 4: Reviews Complete, Docs/Done

#741 Bump version to 3.0.1
  plugin.json
  server/manifest.go
  webapp/src/manifest.ts
Labels: 4: Reviews Complete, QA Review Done
