Repository mattermost/mattermost-plugin-jira, pull requests merged in 2022-03, with the labels that each got.

#844 Require Mattermost 6.5.0
  plugin.json
Labels: 4: Reviews Complete

#847 Removed EnableWebhookEventLogging setting
  plugin.json
Labels: 4: Reviews Complete, AutoMerge, QA Review Done

#846 Release v3.2.0
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: 4: Reviews Complete, QA Review Done, Type/Task
