Repository mattermost/mattermost-plugin-jira, pull requests merged in 2023-12, with the labels that each got.

#938 [GH-558] Fix issue: /jira assign should accept @username
  server/command.go
  server/command_test.go
  server/issue.go
  server/user.go
  server/user_test.go
Labels: 4: Reviews Complete, Contributor

#1002 Fix the issue with "AtlassianSecurityContext" being nil after migration to oauth
  server/instance_cloud_oauth.go
  server/instance_cloud_oauth_migration_test.go
  server/kv.go
  server/mock_kv_store.go
Labels: 2: Dev Review, 3: QA Review

#887 [GH-774] Add tooltip to Jira ticket links
  server/constants.go
  server/http.go
  server/issue.go
  webapp/src/action_types/index.js
  webapp/src/actions/index.ts
  webapp/src/components/default_avatar/defaultAvatar.scss
  webapp/src/components/default_avatar/default_avatar.tsx
  webapp/src/components/jira_ticket_tooltip/index.ts
  webapp/src/components/jira_ticket_tooltip/jira_ticket_tooltip.test.tsx
  webapp/src/components/jira_ticket_tooltip/jira_ticket_tooltip.tsx
  webapp/src/components/jira_ticket_tooltip/ticketStyle.scss
  webapp/src/plugin.tsx
  webapp/src/reducers/index.js
  webapp/src/selectors/index.ts
  webapp/src/testdata/get-ticket-metadata-for-tooltip.ts
  webapp/src/types/tooltip.ts
  webapp/src/utils/jira_issue_metadata.test.tsx
  webapp/src/utils/jira_issue_metadata.tsx
Labels: 4: Reviews Complete, Contributor

#983 [GH-939]: Updated the message for webhookURL in step 2 of plugin setup
  server/setup_flow.go
Labels: 4: Reviews Complete

#1004 Fix full fetch logic (resolves #955)
  server/client_cloud.go
Labels: 3: QA Review, Contributor
