Repository mattermost/mattermost-plugin-jira, pull requests merged in 2023-03, with the labels that each got.

#915 [GH-912]:Fixed issue "Handle error case where issuetypes are not available" of Jira plugin
  server/client.go
  server/client_cloud.go
  server/client_server.go
  server/issue.go
  server/plugin.go
Labels: 4: Reviews Complete, Contributor

#919 [GH-912]:Cherry picked changes from #PR 915
  server/client.go
  server/client_cloud.go
  server/client_server.go
  server/issue.go
  server/plugin.go
Labels: QA Review Done, Contributor

#917 Release v3.2.4
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: 4: Reviews Complete

#922 [MM-51269] Log errors from telemetry events
  server/command.go
  server/plugin.go
  server/setup_flow.go
  server/telemetry.go
  server/user.go
Labels: 4: Reviews Complete

#918 Add Jira Docker development environment
  build/custom.mk
  docker-compose.yml
  docs/development/environment.md
Labels: 4: Reviews Complete

#926 [MM-51751] Fix regex for tags trigger in CI/CD
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: 4: Reviews Complete

#929 fix rudder key secret name
  build/custom.mk
Labels: 4: Reviews Complete
