Repository mattermost/mattermost-plugin-jira, pull requests merged in 2023-02, with the labels that each got.

#906 Release 3.2.3
  plugin.json
  server/issue.go
  server/manifest.go
  webapp/src/manifest.js
Labels: 4: Reviews Complete

#911 Migrate from CircleCI to Github Actions
  .circleci/config.yml
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .nvmrc
  webapp/package.json
Labels: 4: Reviews Complete

#903 Fixed Path Traversal: `dir/../../filename` in moment.locale
  webapp/package-lock.json
Labels: 4: Reviews Complete, Contributor

#913 Improve error handling in `OnSendDailyTelemetry`
  server/plugin.go
Labels: 4: Reviews Complete, AutoMerge

#782 [GH-779]: DOC: Images in plugin docs now have descriptive names
  docs/.gitbook/assets/attach-from-post.png
  docs/.gitbook/assets/create-from-post.png
  docs/.gitbook/assets/jira-slash-command.png
  docs/.gitbook/assets/mention-notification.png
  docs/.gitbook/assets/restrict-jira-users.png
  docs/.gitbook/assets/restrict-mattermost-users.png
  docs/.gitbook/assets/ticket-created.png
  docs/administrator-guide/notification-management.md
  docs/end-user-guide/using-jira-commands.md
  docs/feature-summary.md
Labels: 2: Dev Review

#879 [GH-819]:Create issue modal crashes when assignee is selected before switching projects
  webapp/src/components/data_selectors/jira_user_selector/jira_user_selector.tsx
  webapp/src/components/modals/create_issue/create_issue_form.tsx
  webapp/src/types/model.ts
Labels: 4: Reviews Complete

#821 Fixed plugin failure on Issue with no priority.
  server/issue.go
Labels: 4: Reviews Complete, Contributor
