Repository mattermost/mattermost-plugin-jira, pull requests merged in 2023-08, with the labels that each got.

#953 Fixed issue: Comment notification not working after implementing OAuth2 and Added PKCE code for OAuth2
  assets/templates/oauth2/complete.html
  readme.md
  server/client.go
  server/command.go
  server/instance_cloud_oauth.go
  server/instances.go
  server/issue.go
  server/kv.go
  server/setup_flow.go
  server/user_cloud_oauth.go
  server/utils.go
  server/webhook.go
  server/webhook_jira.go
Labels: 3: QA Review, Contributor

#964 Don't log unsupported webhook events as errors
  server/webhook.go
  server/webhook_parser.go
  server/webhook_worker.go
Labels: 4: Reviews Complete

#949 MM-51310 Implement OAuth2 Authentication (reopened)
  assets/templates/oauth2/complete.html
  readme.md
  server/client.go
  server/command.go
  server/http.go
  server/instance.go
  server/instance_cloud.go
  server/instance_cloud_oauth.go
  server/instance_server.go
  server/instances.go
  server/instances_test.go
  server/issue.go
  server/issue_parser.go
  server/kv.go
  server/kv_mock_test.go
  server/plugin.go
  server/setup_flow.go
  server/user.go
  server/user_cloud_oauth.go
  server/utils.go
  server/webhook.go
  server/webhook_jira.go
Labels: 3: QA Review

#951 [MM-52755] Change user disconnect to HTTP POST
  assets/templates/oauth1/complete.html
  server/http.go
  server/user_server.go
Labels: 4: Reviews Complete, Contributor

#961 [GH-954]:Fixed issue 'DM comment notifications not working'
  server/testdata/webhook-cloud-comment-created-mention-user.json
  server/testdata/webhook-server-issue-updated-commented-mention-user.json
  server/utils.go
  server/webhook_http_test.go
Labels: 3: QA Review
