Repository mattermost/mattermost-plugin-jira, pull requests merged in 2023-11, with the labels that each got.

#995 [GH-971] Support Jira migration to Oauth
  server/command.go
  server/instance_cloud_oauth.go
  server/instances.go
  server/kv.go
  server/setup_flow.go
  server/webhook_jira.go
Labels: 2: Dev Review, 3: QA Review

#962 [GH-957]: Fixed issue 'UI for the "Create Subscription" button'
  webapp/src/components/modals/channel_subscriptions/channel_subscriptions_modal.scss
  webapp/src/components/modals/channel_subscriptions/select_channel_subscription.tsx
Labels: 3: QA Review, 1: UX Review

#988 [MI-54922] Replaced the "text/template" package with "html/template"
  server/command.go
  server/command_test.go
  server/http.go
  server/plugin.go
  server/user_cloud.go
  server/user_cloud_oauth.go
  server/user_server.go
Labels: 4: Reviews Complete
