Repository mattermost/mattermost-plugin-jira, pull requests merged in 2024-01, with the labels that each got.

#1013 [MM-49] Fix invalid Jira links in posts
  server/instance_cloud_oauth.go
Labels: 2: Dev Review

#914 [GH-902]:Added check to uninstall server if not found in KV store
  server/instances.go
Labels: 3: QA Review, Contributor

#904 [GH-830]: Explained the jira subscription modal in the doc
  readme.md
  webapp/src/components/modals/channel_subscriptions/__snapshots__/edit_channel_subscription.test.tsx.snap
  webapp/src/components/modals/channel_subscriptions/channel_subscriptions_modal.scss
  webapp/src/components/modals/channel_subscriptions/edit_channel_subscription.tsx
Labels: 4: Reviews Complete, Contributor

#1005 [GH-1003] Update Readme 'What are notifications?' section screenshot
  assets/attach-from-post.png
  readme.md
Labels: 4: Reviews Complete, Contributor
