Repository mattermost/mattermost-plugin-jira, pull requests merged in 2024-07, with the labels that each got.

#1082 fix: using a safer way to compare errors
  server/webhook_worker.go
Labels: 4: Reviews Complete, Contributor

#1079 Remove co-maintainer from readme
  readme.md
Labels: 4: Reviews Complete

#1092 [MM-996]: removed jwt instance from setup autocomplete
  server/command.go
Labels: 2: Dev Review

#1091 [GH-1087] Add "updated_priority" event param for legacy webhooks
  server/webhook_http.go
Labels: 2: Dev Review

#1089 [GH-1078]: fixed the alignment issue of loading ellipses
  webapp/src/components/loading.tsx
  webapp/src/components/modals/channel_subscriptions/__snapshots__/edit_channel_subscription.test.tsx.snap
Labels: 4: Reviews Complete

#1095 [GH-993]: added support for subtasks in subscriptions
  webapp/src/components/modals/channel_subscriptions/__snapshots__/edit_channel_subscription.test.tsx.snap
  webapp/src/components/modals/channel_subscriptions/edit_channel_subscription.tsx
  webapp/src/components/modals/create_issue/__snapshots__/create_issue_form.test.tsx.snap
  webapp/src/components/modals/create_issue/create_issue_form.tsx
  webapp/src/utils/jira_issue_metadata.tsx
Labels: 2: Dev Review
