Repository mattermost/mattermost-plugin-jira, pull requests merged in 2024-03, with the labels that each got.

#870 [GH-768]: Fixed Issue /Jira Connect doesn't open mattermost's subpath url
  server/plugin.go
  server/user_cloud.go
  server/user_server.go
  webapp/src/actions/index.ts
  webapp/src/selectors/index.ts
Labels: 3: QA Review, Contributor

#1033 [GH-1032] Fix NPE if reporter is blank during issue creation
  server/issue_parser.go
  server/issue_parser_test.go
Labels: 2: Dev Review, 3: QA Review

#969 [GH-855] Save user's last used field values
  server/command.go
  server/issue.go
  server/subscribe.go
  server/user.go
  webapp/src/components/jira_instance_and_project_selector/jira_instance_and_project_selector.test.tsx
  webapp/src/components/jira_instance_and_project_selector/jira_instance_and_project_selector.tsx
  webapp/src/components/modals/attach_comment_modal/attach_comment_form.tsx
  webapp/src/components/modals/channel_subscriptions/edit_channel_subscription.test.tsx
  webapp/src/components/modals/channel_subscriptions/edit_channel_subscription.tsx
  webapp/src/components/modals/create_issue/create_issue_form.tsx
  webapp/src/types/model.ts
Labels: 4: Reviews Complete

#1034 [MM-54994] Use local requests instead of HTTP requests in the flow library
  go.mod
  go.sum
  server/issue_test.go
  server/plugin.go
  server/setup_flow.go
Labels: 3: QA Review
