Repository mattermost/mattermost-plugin-jira, pull requests merged in 2025-03, with the labels that each got.

#894 [GH-626]: Supported filtering on comment visibility for subscriptions
  .gitignore
  server/client.go
  server/http.go
  server/issue.go
  server/subscribe.go
  webapp/src/actions/index.ts
  webapp/src/components/data_selectors/jira_commentvisibility_selector/index.ts
  webapp/src/components/data_selectors/jira_commentvisibility_selector/jira_commentvisibility_selector.tsx
  webapp/src/components/modals/channel_subscriptions/__snapshots__/channel_subscription_filter.test.tsx.snap
  webapp/src/components/modals/channel_subscriptions/__snapshots__/channel_subscription_filters.test.tsx.snap
  webapp/src/components/modals/channel_subscriptions/__snapshots__/edit_channel_subscription.test.tsx.snap
  webapp/src/components/modals/channel_subscriptions/channel_subscription_filter.tsx
  webapp/src/utils/jira_issue_metadata.test.tsx
  webapp/src/utils/jira_issue_metadata.tsx
Labels: 4: Reviews Complete, QA Review Done

#1127 [MM-794]: Fixed the issue of fields not prefilled when creating issue with custom fields
  server/client.go
Labels: 4: Reviews Complete

#1133 [MM-898]: Fixed TS errors in multiple webapp files
  webapp/src/actions/index.ts
  webapp/src/components/jira_fields.tsx
  webapp/src/components/modals/attach_comment_modal/index.ts
  webapp/src/components/modals/channel_subscriptions/index.ts
  webapp/src/components/modals/connect_modal/connect_modal_form.tsx
  webapp/src/components/modals/connect_modal/index.ts
  webapp/src/components/modals/connect_modal/props.ts
  webapp/src/components/modals/create_issue/index.ts
  webapp/src/components/modals/disconnect_modal/disconnect_modal_form.tsx
  webapp/src/components/modals/disconnect_modal/index.ts
  webapp/src/components/react_select_setting.tsx
  webapp/src/selectors/index.ts
  webapp/src/types/model.ts
  webapp/src/types/store.ts
Labels: 4: Reviews Complete

#1122 [MM-571]: Fixed the issue of receiving Jira subscription after the channel is archived
  server/webhook_worker.go
Labels: 4: Reviews Complete

#1134 [MM-1121]: Fix epic selector not displaying options if field is renamed in Jira
  webapp/src/components/data_selectors/jira_epic_selector/jira_epic_selector.tsx
Labels: 3: QA Review
