Repository mattermost/mattermost-plugin-jira, pull requests merged in 2025-05, with the labels that each got.

#1187 [GH-768] Fix redirect connect doesn't open mattermost's subpath url
  webapp/src/actions/index.ts
Labels: 2: Dev Review, 3: QA Review, Contributor

#1201 Added support for Enterprise Advanced license
  .github/workflows/ci.yml
  .golangci.yml
  Makefile
  go.mod
  go.sum
  readme.md
  server/enterprise/license.go
  server/instances.go
  server/instances_test.go
  server/issue.go
  server/utils/byte_size.go
  server/utils/types/byte_size.go
Labels: 2: Dev Review

#1111 [MM-803]: Added a slash command to set a default jira instance in case of multiple instances
  server/command.go
  server/instances.go
  server/user.go
Labels: 3: QA Review

#1177 Converted reducer/index.js to TS
  webapp/src/reducers/index.ts
Labels: 3: QA Review, Contributor
