Repository mattermost/mattermost-plugin-jira, pull requests merged in 2025-02, with the labels that each got.

#1155 Fix multi line code block rendering in Jira subscription post
  server/webhook_parser.go
  server/webhook_parser_misc_test.go
Labels: 4: Reviews Complete

#1171 fixed issue of plugin config not prefilling from previous build
  server/plugin.go
Labels: 4: Reviews Complete, QA Review Done

#1140 [MM-959]: Added type for redux store and resolved some TS errors
  webapp/src/actions/index.ts
  webapp/src/components/modals/attach_comment_modal/index.ts
  webapp/src/components/modals/channel_subscriptions/index.ts
  webapp/src/components/modals/connect_modal/index.ts
  webapp/src/components/modals/create_issue/index.ts
  webapp/src/components/modals/disconnect_modal/disconnect_modal_form.tsx
  webapp/src/components/modals/disconnect_modal/index.ts
  webapp/src/selectors/index.ts
  webapp/src/types/model.ts
  webapp/src/types/store.ts
Labels: 4: Reviews Complete

#1176 Add aider files to gitignore
  .gitignore
Labels: 2: Dev Review
